//nolint:testpackage // reaches the unexported span search, geometry and thread helpers under test
package renderer

// Cross-platform precision measurements for the CPU renderer (PLAN.md Task
// 10.20). The method, the full matrix, and what emulation does and does not
// establish are written up in docs/renderer-precision-measurements.md.
//
// The oracle here is the byte-exact contract in docs/renderer-correctness.md,
// which has two halves, and this file asserts both:
//
//   - Within one process, rendered bytes and the exact cost must not depend on
//     the SIMD tier or on how the row walk is sharded. Every case is rendered
//     at every tier fit.SupportedTiers() reports and at several shard counts,
//     and all of them are compared to the same buffer.
//
//   - Across processes, they must not depend on the architecture either. That
//     cannot be checked inside one binary, so each case carries a recorded
//     SHA-256 digest of its pixel buffer and its cost. The digests below were
//     produced on amd64 and are asserted unchanged on arm64; a change to any of
//     them is a change to rendered output and needs the same justification as
//     any other.
//
// The scene data is generated by a local SplitMix64 rather than math/rand so
// that the digests depend on nothing outside this file.

import (
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"image"
	"math"
	"runtime"
	"testing"

	"github.com/cwbudde/circlefit/internal/fit"
)

const (
	// precisionQ16 is one Q16.16 unit expressed in float64: the step of the
	// renderer's fixed-point geometry. It is a power of two, so every offset
	// built from it below is exact in binary64.
	precisionQ16 = 1.0 / 65536.0
	// precisionQ16Half is half a Q16.16 unit. Adding it to an integer puts
	// floatToQ16's math.Round argument exactly on a .5 tie, which is the
	// rounding boundary the fractional cases exist to pin.
	precisionQ16Half = precisionQ16 / 2
)

// precisionCanvasKind selects the base canvas a scene renders onto. It is an
// axis of the matrix rather than a detail: an opaque canvas takes the SIMD span
// compositors and a translucent one takes the per-pixel Porter-Duff path, so a
// boundary case measured only on white measures only half the renderer.
type precisionCanvasKind int

const (
	precisionCanvasWhite precisionCanvasKind = iota
	precisionCanvasOpaque
	precisionCanvasTranslucent
)

// precisionScene is one case of the matrix.
type precisionScene struct {
	name          string
	width, height int
	canvas        precisionCanvasKind
	circles       []fit.Circle
}

// precisionRNG is SplitMix64. The generator is local, and its output is defined
// entirely by uint64 arithmetic, so the reference images and the randomized
// circle draws are identical on every architecture and cannot drift with a
// change to math/rand.
type precisionRNG struct {
	state uint64
}

func newPrecisionRNG(seed uint64) *precisionRNG {
	return &precisionRNG{state: seed}
}

func (r *precisionRNG) next() uint64 {
	r.state += 0x9e3779b97f4a7c15
	mixed := r.state
	mixed = (mixed ^ (mixed >> 30)) * 0xbf58476d1ce4e5b9
	mixed = (mixed ^ (mixed >> 27)) * 0x94d049bb133111eb

	return mixed ^ (mixed >> 31)
}

// unitFloat returns a value in [0,1) built from 53 mantissa bits.
func (r *precisionRNG) unitFloat() float64 {
	return float64(r.next()>>11) / float64(uint64(1)<<53)
}

func (r *precisionRNG) nextByte() uint8 {
	return uint8(r.next() >> 56)
}

// precisionImage builds a deterministic NRGBA image. Opaque images pin alpha at
// 255 so the renderer selects its span compositors; translucent ones vary it so
// the general per-pixel path is exercised instead.
func precisionImage(width, height int, seed uint64, opaque bool) *image.NRGBA {
	rng := newPrecisionRNG(seed)
	img := image.NewNRGBA(image.Rect(0, 0, width, height))

	for i := 0; i < len(img.Pix); i += 4 {
		img.Pix[i+0] = rng.nextByte()
		img.Pix[i+1] = rng.nextByte()
		img.Pix[i+2] = rng.nextByte()

		if opaque {
			img.Pix[i+3] = 255
			continue
		}

		// Keep a spread of alphas including both extremes.
		img.Pix[i+3] = rng.nextByte()
	}

	return img
}

func precisionReference(width, height int) *image.NRGBA {
	return precisionImage(width, height, 0x5150_1020_0001, true)
}

func (s precisionScene) baseCanvas() *image.NRGBA {
	switch s.canvas {
	case precisionCanvasWhite:
		return nil
	case precisionCanvasOpaque:
		return precisionImage(s.width, s.height, 0x5150_1020_0002, true)
	case precisionCanvasTranslucent:
		return precisionImage(s.width, s.height, 0x5150_1020_0003, false)
	default:
		return nil
	}
}

// precisionRender renders one scene at the given shard count and returns an
// independent copy of the pixels together with the exact cost. The buffer is
// copied because CPURenderer reuses it.
func precisionRender(scene precisionScene, threads int) ([]byte, float64) {
	reference := precisionReference(scene.width, scene.height)
	params := encodeCircles(scene.circles)

	var renderer *CPURenderer
	if base := scene.baseCanvas(); base != nil {
		renderer = NewCPURendererWithCanvas(reference, base, len(scene.circles))
	} else {
		renderer = NewCPURenderer(reference, len(scene.circles))
	}

	renderer.SetThreads(threads)

	rendered := renderer.Render(params)
	pixels := append([]byte(nil), rendered.Pix...)

	return pixels, renderer.Cost(params)
}

// precisionDigest folds the rendered bytes and the exact cost into one hash.
// The cost is included deliberately: it routes through the SSD kernels, so the
// digest covers the tier-dispatched cost path as well as the compositors.
func precisionDigest(pixels []byte, cost float64) string {
	sum := sha256.New()
	_, _ = sum.Write(pixels)

	var costBits [8]byte

	binary.BigEndian.PutUint64(costBits[:], math.Float64bits(cost))
	_, _ = sum.Write(costBits[:])

	return hex.EncodeToString(sum.Sum(nil))
}

// precisionShardCounts returns shard counts that are valid at any core count.
// Nothing here may name a fixed worker count: SetThreads caps at GOMAXPROCS and
// at the image height, and the macOS ARM64 CI runner has three processors, so a
// test asserting on four workers fails there and nowhere else.
func precisionShardCounts(height int) []int {
	candidates := []int{1, 2, 3, runtime.GOMAXPROCS(0), height}

	counts := make([]int, 0, len(candidates))
	seen := make(map[int]bool, len(candidates))

	for _, candidate := range candidates {
		effective := effectiveThreadCount(candidate, height)
		if seen[effective] {
			continue
		}

		seen[effective] = true

		counts = append(counts, effective)
	}

	return counts
}

// assertPixelsEqual reports the first differing pixel rather than the buffers,
// so a cross-tier or cross-shard failure names a coordinate and a channel.
func assertPixelsEqual(t *testing.T, got, want []byte, width int, context string) {
	t.Helper()

	if len(got) != len(want) {
		t.Fatalf("%s: pixel buffer length = %d, want %d", context, len(got), len(want))
	}

	for i := range want {
		if got[i] == want[i] {
			continue
		}

		pixel := i / 4
		t.Fatalf("%s: pixel (%d,%d) channel %d = %d, want %d", context, pixel%width, pixel/width, i%4, got[i], want[i])
	}
}

// precisionDigests records what every named scene renders to, including the
// row-shard sweep's own scene at the end of the map. Each value is
// the SHA-256 of the scene's pixel buffer followed by the eight bytes of its
// exact cost, and each is an architecture- and tier-independent constant: the
// values below were measured on amd64 and are asserted unchanged by the ARM64
// rows of ci-native-simd.yml. Changing one is changing rendered output.
//
// Scenes that share a value share it on purpose, and the sharing is part of the
// measurement: the four clipping/outside_* cases must all leave the canvas
// untouched, the min_square selection pair must not depend on which search
// runs, and an inclusive span edge must not move when the radius grows.
// precisionUntouchedCanvas is what a scene renders to when nothing is painted:
// the configured base canvas, byte for byte. All four clipping/outside_* cases
// share it, and their sharing it is the assertion.
const precisionUntouchedCanvas = "0adbcf39a93f81cb04a0d78dc7d9bbd0a44107ff55dec0a9486013e20d0319d8"

var precisionDigests = map[string]string{
	"fractional/half_pixel_center":          "edc4bb99d4f1c5f38f780582c2a22a2f98ee77b27ae1215d35b40633725b19c1",
	"fractional/quarter_and_eighth":         "4726c9f9c60b20e27f827cbd8be17006412404365788e8692e8355db4082859d",
	"fractional/q16_rounding_tie":           "c8952cc307002a82ad9c230192b480a4cc1dc9fd38aab1b9f03e1d8f8f735d55",
	"fractional/center_pixel_tie_up":        "e5751575e620b27a6b90b7fe1da2ed46e706ad9bd70c468d87b5d500443a2d09",
	"fractional/center_pixel_tie_down":      "e5751575e620b27a6b90b7fe1da2ed46e706ad9bd70c468d87b5d500443a2d09",
	"fractional/translucent_canvas":         "a455109690f3d274cca8cf75a4c31de943bf6e88d0f09e37a76aa07bd8856a07",
	"tangent/integer_radius":                "0a8371cff5d20053c34cb50bdc8e294db7ca66fd1965c8d4662e1c480e4c6973",
	"tangent/radius_one_q16_below":          "2ff0610edfcdf3f4a2b7d06a620686522878015c99e0bceeb7748d5a35c65eba",
	"tangent/radius_one_q16_above":          "0a8371cff5d20053c34cb50bdc8e294db7ca66fd1965c8d4662e1c480e4c6973",
	"tangent/single_pixel_row":              "39496bed945444a19d539ad709890a07ce62c94e28f2763f43ad7e4f6cd64235",
	"tangent/half_integer_center":           "983fb4ec5c01aa59875f801b4fb1c3e757ee6310db82dee18d20368b979b2dbf",
	"radius/one_integer_center":             "570fe8b288eaa29488522b233b5898a593ef948b11c786368ad667a5b2fab045",
	"radius/one_fractional_center":          "4a69a000bacedc0665e052b02eafe3dcd7b295724ff0cce6f879bc6620437f4d",
	"radius/minimum_opacity":                "bc59dabe4235d93597e9588699a94c1dedfc3b17e8626e2cca95882a6402ed7f",
	"radius/canvas_maximum":                 "36e75b523710d42b184b1c56eb5765b224006c63334c1a253cf6346580cec4db",
	"radius/q16_maximum":                    "efd1d071947d149aee983f67d970d47785cd14e6fc09ab0a4cbe83db83d9c877",
	"radius/beyond_q16_range":               "7a74d3f4fff60d0c5642705f784907af1ad9731433f216c7178ac55bd828219e",
	"radius/center_beyond_q16_range":        "c54de7ad2b7fc277fe5b482a3933fe7ad94b26285b921cd8206feb8adb64d0ec",
	"clipping/partial_left":                 "24cf108018a4700a46ea1740be0493606a9d4b9b71735edd3373fedf7093bb17",
	"clipping/outside_left":                 precisionUntouchedCanvas,
	"clipping/partial_right":                "a2f2a10c3ba4a3f8a348447292b11f17197a4cb90fbdd03c12658e46078e1cca",
	"clipping/outside_right":                precisionUntouchedCanvas,
	"clipping/partial_top":                  "f4e476b7eafda37584aa2ed0d73840567f89e0d4a20c74b591b3b1236d44b0b9",
	"clipping/outside_top":                  precisionUntouchedCanvas,
	"clipping/partial_bottom":               "01177a0d96cdd85914b9a571b123344c36dca0f297d3ab206b0953a2dcc61262",
	"clipping/outside_bottom":               precisionUntouchedCanvas,
	"clipping/larger_than_canvas":           "1fd0bd88cee0a8171521a28d737455278aee4942c8f9bfe571a715dbb3793ef1",
	"batch/stride_guards_width_63":          "3edc04efebe272f58fd8e24550939394bc0f0d169b2c1d07b1a9b366cda7da1b",
	"batch/stride_guards_width_64":          "33c6e393107f870071bd600831acca4da0b475dc4811ac55bfa88eef1dc7bbc8",
	"batch/stride_guards_width_65":          "e9abe236663c446bedfa01c73b58bdd09d9a64017c602a695499a292117efc78",
	"batch/min_square_selection_batched":    "b462c568d84635535a9a059e46a468fee24f8bf43d17d01dd92c23aa29f5ebdd",
	"batch/min_square_selection_one_pixel":  "b462c568d84635535a9a059e46a468fee24f8bf43d17d01dd92c23aa29f5ebdd",
	"batch/min_square_inclusive_edge":       "3845c66b800dd271a5bfadb60c1c6b30394a8b28102eb3374b59fbea4c7e877e",
	"batch/min_square_inclusive_edge_below": "a6595fa5288a8efc82363f9462a99d7fc6cba25298f27d6328f2fdc50e9bfe66",
	"batch/min_square_inclusive_edge_above": "3845c66b800dd271a5bfadb60c1c6b30394a8b28102eb3374b59fbea4c7e877e",

	// The row-shard sweep's scene. It is not part of precisionScenes(), but its
	// single-threaded render is the oracle every shard count is compared
	// against, so it is anchored here for the same reason and by the same
	// mechanism as the scenes above.
	"sharding": "7544292a538b3fd517cc8cc3f438ae2bc8e82e957ea0ff923bddd06bb773b0a7",
}

// precisionScenes is the named half of the matrix. Every case the plan item
// lists appears here except the randomized draws and the row-shard sweep, which
// have their own tests below.
func precisionScenes() []precisionScene {
	scenes := make([]precisionScene, 0, 32)
	scenes = append(scenes, precisionFractionalScenes()...)
	scenes = append(scenes, precisionTangentScenes()...)
	scenes = append(scenes, precisionRadiusScenes()...)
	scenes = append(scenes, precisionClippingScenes()...)
	scenes = append(scenes, precisionBatchScenes()...)

	return scenes
}

// precisionFractionalScenes covers centers and radii off the pixel grid,
// including the values whose Q16.16 conversion lands exactly on a rounding tie
// and the values that straddle the int(x+0.5) center-pixel boundary the span
// search starts from.
func precisionFractionalScenes() []precisionScene {
	return []precisionScene{
		{
			name: "fractional/half_pixel_center", width: 33, height: 25, canvas: precisionCanvasOpaque,
			circles: []fit.Circle{
				{X: 16.5, Y: 12.5, R: 6.5, CR: 0.2, CG: 0.6, CB: 0.9, Opacity: 0.75},
				{X: 8.5, Y: 6.5, R: 3.5, CR: 0.9, CG: 0.2, CB: 0.1, Opacity: 0.5},
			},
		},
		{
			name: "fractional/quarter_and_eighth", width: 33, height: 25,
			circles: []fit.Circle{
				{X: 16.25, Y: 12.75, R: 6.125, CR: 0.35, CG: 0.15, CB: 0.55, Opacity: 0.65},
				{X: 9.875, Y: 5.125, R: 4.375, CR: 0.05, CG: 0.85, CB: 0.45, Opacity: 1},
			},
		},
		{
			// Every coordinate multiplies to exactly n + 0.5 in Q16.16, so
			// floatToQ16's math.Round decides the tie. Both signs are present
			// because math.Round breaks ties away from zero.
			name: "fractional/q16_rounding_tie", width: 33, height: 25, canvas: precisionCanvasOpaque,
			circles: []fit.Circle{
				{
					X: 12 + precisionQ16Half, Y: 12 + precisionQ16Half, R: 6 + precisionQ16Half,
					CR: 0.4, CG: 0.4, CB: 0.9, Opacity: 0.8,
				},
				{
					X: -(4 + precisionQ16Half), Y: -(4 + precisionQ16Half), R: 8 + precisionQ16Half,
					CR: 0.9, CG: 0.4, CB: 0.4, Opacity: 0.6,
				},
			},
		},
		{
			// int(X+0.5) rounds up here and down in the next scene, which moves
			// the pixel the center-out search starts from by one.
			name: "fractional/center_pixel_tie_up", width: 33, height: 25,
			circles: []fit.Circle{
				{X: 7.5, Y: 11.5, R: 5.25, CR: 0.1, CG: 0.7, CB: 0.3, Opacity: 0.9},
			},
		},
		{
			name: "fractional/center_pixel_tie_down", width: 33, height: 25,
			circles: []fit.Circle{
				{X: 7.5 - precisionQ16Half, Y: 11.5, R: 5.25, CR: 0.1, CG: 0.7, CB: 0.3, Opacity: 0.9},
			},
		},
		{
			name: "fractional/translucent_canvas", width: 33, height: 25, canvas: precisionCanvasTranslucent,
			circles: []fit.Circle{
				{X: 16.5, Y: 12.5, R: 7.75, CR: 0.3, CG: 0.5, CB: 0.7, Opacity: 0.45},
				{X: 11.125, Y: 9.875, R: 5.5, CR: 0.8, CG: 0.2, CB: 0.6, Opacity: 0.001},
			},
		},
	}
}

// precisionTangentScenes covers rows where the scanline barely reaches the
// disc: an integer radius makes the extreme row touch at exactly one sample,
// and one Q16.16 unit either side of it decides whether that row exists at all.
func precisionTangentScenes() []precisionScene {
	return []precisionScene{
		{
			name: "tangent/integer_radius", width: 21, height: 21, canvas: precisionCanvasOpaque,
			circles: []fit.Circle{
				{X: 10, Y: 10, R: 4, CR: 0.15, CG: 0.35, CB: 0.95, Opacity: 1},
			},
		},
		{
			name: "tangent/radius_one_q16_below", width: 21, height: 21, canvas: precisionCanvasOpaque,
			circles: []fit.Circle{
				{X: 10, Y: 10, R: 4 - precisionQ16, CR: 0.15, CG: 0.35, CB: 0.95, Opacity: 1},
			},
		},
		{
			name: "tangent/radius_one_q16_above", width: 21, height: 21, canvas: precisionCanvasOpaque,
			circles: []fit.Circle{
				{X: 10, Y: 10, R: 4 + precisionQ16, CR: 0.15, CG: 0.35, CB: 0.95, Opacity: 1},
			},
		},
		{
			// The extreme row of this circle touches exactly one pixel.
			name: "tangent/single_pixel_row", width: 21, height: 21,
			circles: []fit.Circle{
				{X: 10.5, Y: 10, R: 3, CR: 0.6, CG: 0.1, CB: 0.4, Opacity: 0.85},
			},
		},
		{
			// Half-integer center in both axes: the tangent row's nearest
			// sample sits half a pixel off the center in x as well as y.
			name: "tangent/half_integer_center", width: 21, height: 21,
			circles: []fit.Circle{
				{X: 10.5, Y: 10.5, R: 2.5, CR: 0.25, CG: 0.75, CB: 0.25, Opacity: 0.7},
			},
		},
	}
}

// precisionRadiusScenes covers the smallest meaningful circle and the largest
// ones the canvas bounds and the Q16.16 range admit, including the first radius
// that leaves that range and therefore falls back to the float64 oracle.
func precisionRadiusScenes() []precisionScene {
	return []precisionScene{
		{
			name: "radius/one_integer_center", width: 9, height: 9, canvas: precisionCanvasOpaque,
			circles: []fit.Circle{
				{X: 4, Y: 4, R: fit.MinCircleRadius, CR: 1, CG: 0, CB: 0, Opacity: 1},
			},
		},
		{
			name: "radius/one_fractional_center", width: 9, height: 9, canvas: precisionCanvasOpaque,
			circles: []fit.Circle{
				{X: 4.5, Y: 4.5, R: fit.MinCircleRadius, CR: 0, CG: 1, CB: 0, Opacity: 1},
			},
		},
		{
			name: "radius/minimum_opacity", width: 9, height: 9, canvas: precisionCanvasOpaque,
			circles: []fit.Circle{
				{X: 4, Y: 4, R: fit.MinCircleRadius, CR: 0, CG: 0, CB: 1, Opacity: fit.MinCircleOpacity},
			},
		},
		{
			// fit.NewBounds caps the radius at max(width, height); this is that
			// circle, centered, with a center at the bounds' own extreme too.
			name: "radius/canvas_maximum", width: 48, height: 32, canvas: precisionCanvasOpaque,
			circles: []fit.Circle{
				{X: 23.5, Y: 15.5, R: 48, CR: 0.45, CG: 0.55, CB: 0.65, Opacity: 0.4},
				{X: -24, Y: -16, R: 48, CR: 0.65, CG: 0.55, CB: 0.45, Opacity: 0.3},
			},
		},
		{
			// Near the largest radius signed Q16.16 can hold, so the
			// fixed-point walk runs with its widest products. The center is
			// pushed off-canvas by almost the same amount so the disc edge
			// still crosses the image and the case has a boundary to get
			// wrong.
			name: "radius/q16_maximum", width: 33, height: 25,
			circles: []fit.Circle{
				{X: -32700, Y: 12, R: 32720, CR: 0.5, CG: 0.25, CB: 0.75, Opacity: 0.2},
			},
		},
		{
			// R is one unit past the Q16.16 range: newFixedCircleQ16 refuses
			// the conversion and the row walk falls back to the float64 oracle.
			name: "radius/beyond_q16_range", width: 33, height: 25,
			circles: []fit.Circle{
				{X: -32750, Y: 12, R: 32768, CR: 0.5, CG: 0.25, CB: 0.75, Opacity: 0.2},
			},
		},
		{
			// A center outside the Q16.16 range takes the same fallback.
			name: "radius/center_beyond_q16_range", width: 33, height: 25,
			circles: []fit.Circle{
				{X: 32768, Y: 12, R: 32760, CR: 0.7, CG: 0.3, CB: 0.1, Opacity: 0.5},
			},
		},
	}
}

// precisionClippingScenes covers circles partly and wholly beyond each of the
// four edges, and one larger than the canvas in both dimensions.
func precisionClippingScenes() []precisionScene {
	const (
		width  = 17
		height = 13
	)

	edges := []struct {
		name    string
		partial fit.Circle
		outside fit.Circle
	}{
		{
			name:    "left",
			partial: fit.Circle{X: -2.5, Y: 6.5, R: 5.25},
			outside: fit.Circle{X: -9.5, Y: 6.5, R: 4.5},
		},
		{
			name:    "right",
			partial: fit.Circle{X: width + 1.5, Y: 6.5, R: 5.25},
			outside: fit.Circle{X: width + 8.5, Y: 6.5, R: 4.5},
		},
		{
			name:    "top",
			partial: fit.Circle{X: 8.5, Y: -2.5, R: 5.25},
			outside: fit.Circle{X: 8.5, Y: -9.5, R: 4.5},
		},
		{
			name:    "bottom",
			partial: fit.Circle{X: 8.5, Y: height + 1.5, R: 5.25},
			outside: fit.Circle{X: 8.5, Y: height + 8.5, R: 4.5},
		},
	}

	scenes := make([]precisionScene, 0, len(edges)*2+1)

	for _, edge := range edges {
		partial := edge.partial
		partial.CR, partial.CG, partial.CB, partial.Opacity = 0.8, 0.4, 0.2, 0.9

		outside := edge.outside
		outside.CR, outside.CG, outside.CB, outside.Opacity = 0.2, 0.4, 0.8, 1

		scenes = append(scenes,
			precisionScene{
				name: "clipping/partial_" + edge.name, width: width, height: height,
				canvas: precisionCanvasOpaque, circles: []fit.Circle{partial},
			},
			precisionScene{
				name: "clipping/outside_" + edge.name, width: width, height: height,
				canvas: precisionCanvasOpaque, circles: []fit.Circle{outside},
			},
		)
	}

	return append(scenes, precisionScene{
		name: "clipping/larger_than_canvas", width: width, height: height, canvas: precisionCanvasTranslucent,
		circles: []fit.Circle{
			{X: 8.5, Y: 6.5, R: 40, CR: 0.3, CG: 0.9, CB: 0.6, Opacity: 0.55},
		},
	})
}

// precisionBatchScenes covers the span search's eight-pixel batching
// boundaries: circleBatchMinSquare, which selects between the batched and
// one-pixel searches, and the xStart >= 8 and xEnd+7 < width guards that decide
// whether a batched stride may be taken at all. The three canvas widths put the
// right-hand guard exactly on, one below, and one above a multiple of eight.
func precisionBatchScenes() []precisionScene {
	// 7.5 is the smallest radius whose widest row reaches circleBatchMinSquare
	// exactly: 7.5*7.5 == 56.25. An integer center Y puts that row on dy == 0.
	const batchRadius = 7.5

	widths := []int{63, 64, 65}
	scenes := make([]precisionScene, 0, len(widths)+3)

	for _, width := range widths {
		scenes = append(scenes, precisionScene{
			name: fmt.Sprintf("batch/stride_guards_width_%d", width), width: width, height: 24,
			canvas: precisionCanvasOpaque,
			circles: []fit.Circle{
				// Left guard: the search cannot take a stride below x == 8.
				{X: 4, Y: 8, R: 12, CR: 0.9, CG: 0.3, CB: 0.3, Opacity: 0.6},
				// Interior: strides in both directions.
				{X: float64(width) / 2, Y: 12, R: 12, CR: 0.3, CG: 0.9, CB: 0.3, Opacity: 0.6},
				// Right guard: xEnd+7 crosses the width here.
				{X: float64(width) - 5, Y: 16, R: 12, CR: 0.3, CG: 0.3, CB: 0.9, Opacity: 0.6},
			},
		})
	}

	// A quarter-pixel center keeps every span edge away from a coverage tie,
	// so these two scenes differ in nothing but which search runs: crossing
	// circleBatchMinSquare must leave the rendered bytes alone, and their
	// digests being equal is that assertion.
	//
	// The half-pixel pair does the opposite. There the widest row's edge lands
	// exactly on |dx| == R, so the inclusive boundary rule decides two pixels,
	// and one Q16.16 unit less radius drops both.
	return append(scenes,
		precisionScene{
			name: "batch/min_square_selection_batched", width: 64, height: 24, canvas: precisionCanvasOpaque,
			circles: []fit.Circle{
				{X: 32.25, Y: 12, R: batchRadius, CR: 0.25, CG: 0.5, CB: 0.75, Opacity: 0.95},
			},
		},
		precisionScene{
			name: "batch/min_square_selection_one_pixel", width: 64, height: 24, canvas: precisionCanvasOpaque,
			circles: []fit.Circle{
				{X: 32.25, Y: 12, R: batchRadius - precisionQ16, CR: 0.25, CG: 0.5, CB: 0.75, Opacity: 0.95},
			},
		},
		precisionScene{
			name: "batch/min_square_inclusive_edge", width: 64, height: 24, canvas: precisionCanvasOpaque,
			circles: []fit.Circle{
				{X: 32.5, Y: 12, R: batchRadius, CR: 0.25, CG: 0.5, CB: 0.75, Opacity: 0.95},
			},
		},
		precisionScene{
			name: "batch/min_square_inclusive_edge_below", width: 64, height: 24, canvas: precisionCanvasOpaque,
			circles: []fit.Circle{
				{X: 32.5, Y: 12, R: batchRadius - precisionQ16, CR: 0.25, CG: 0.5, CB: 0.75, Opacity: 0.95},
			},
		},
		precisionScene{
			name: "batch/min_square_inclusive_edge_above", width: 64, height: 24, canvas: precisionCanvasOpaque,
			circles: []fit.Circle{
				{X: 32.5, Y: 12, R: batchRadius + precisionQ16, CR: 0.25, CG: 0.5, CB: 0.75, Opacity: 0.95},
			},
		},
	)
}

// TestRendererPrecisionBoundaries is the named half of the matrix. Each scene
// is one subtest, so a failure names the boundary rather than the file.
//
//nolint:paralleltest // forces the process-global SIMD tier, which no two tests may do at once
func TestRendererPrecisionBoundaries(t *testing.T) {
	tiers := fit.SupportedTiers()
	t.Logf("architecture %s, detected tier %s, supported tiers %v", runtime.GOARCH, fit.Tier(), tiers)
	t.Cleanup(fit.ResetTierDetection)

	//nolint:paralleltest // each subtest renders under a forced tier the loop owns
	for _, scene := range precisionScenes() {
		t.Run(scene.name, func(t *testing.T) {
			want, wantCost := precisionRender(scene, 1)

			recorded, ok := precisionDigests[scene.name]
			if !ok {
				t.Fatalf("scene has no recorded digest; measured %q", precisionDigest(want, wantCost))
			}

			if got := precisionDigest(want, wantCost); got != recorded {
				t.Errorf("digest = %q, recorded %q (cost %v)", got, recorded, wantCost)
			}

			// A second render must reproduce the first: the canvas is reused
			// and reset from the configured background.
			repeat, repeatCost := precisionRender(scene, 1)
			assertPixelsEqual(t, repeat, want, scene.width, "repeat render")

			if repeatCost != wantCost {
				t.Errorf("repeat cost = %v, want %v", repeatCost, wantCost)
			}

			for _, tier := range tiers {
				if testing.Short() && tier != fit.Tier() {
					continue
				}

				fit.SetForcedTier(tier)

				for _, threads := range precisionShardCounts(scene.height) {
					got, cost := precisionRender(scene, threads)
					assertPixelsEqual(t, got, want, scene.width, fmt.Sprintf("tier %s, %d shards", tier, threads))

					if cost != wantCost {
						t.Errorf("tier %s, %d shards: cost = %v, want %v", tier, threads, cost, wantCost)
					}
				}

				fit.ResetTierDetection()
			}
		})
	}
}

// precisionRandomScene draws one scene from the full legal parameter range:
// centers up to half a canvas dimension beyond each edge and radii from the
// minimum to max(width, height), which is exactly what fit.NewBounds permits.
func precisionRandomScene(rng *precisionRNG, width, height, circles int) []fit.Circle {
	maxDimension := float64(max(width, height))
	drawn := make([]fit.Circle, circles)

	for i := range drawn {
		drawn[i] = fit.Circle{
			X:       rng.unitFloat()*2*float64(width) - float64(width)/2,
			Y:       rng.unitFloat()*2*float64(height) - float64(height)/2,
			R:       fit.MinCircleRadius + rng.unitFloat()*(maxDimension-fit.MinCircleRadius),
			CR:      rng.unitFloat(),
			CG:      rng.unitFloat(),
			CB:      rng.unitFloat(),
			Opacity: fit.MinCircleOpacity + rng.unitFloat()*(1-fit.MinCircleOpacity),
		}
	}

	return drawn
}

// precisionRandomDigest renders every draw of the sweep and folds all of them
// into one hash, so a single byte anywhere in any draw changes the result.
func precisionRandomDigest(t *testing.T, draws, threads int) string {
	t.Helper()

	const (
		width   = 97
		height  = 71
		circles = 3
		seed    = 0x5150_1020_5EED
	)

	reference := precisionReference(width, height)
	base := precisionImage(width, height, 0x5150_1020_0002, true)
	rng := newPrecisionRNG(seed)
	sum := sha256.New()

	renderer := NewCPURendererWithCanvas(reference, base, circles)
	renderer.SetThreads(threads)

	for range draws {
		params := encodeCircles(precisionRandomScene(rng, width, height, circles))
		_, _ = sum.Write(renderer.Render(params).Pix)

		var costBits [8]byte

		binary.BigEndian.PutUint64(costBits[:], math.Float64bits(renderer.Cost(params)))
		_, _ = sum.Write(costBits[:])
	}

	return hex.EncodeToString(sum.Sum(nil))
}

// TestRendererPrecisionRandomizedCircles sweeps the legal parameter range with
// a documented fixed seed and compares every rendered byte. The two recorded
// digests exist because -short takes the shorter sweep; both are
// architecture-independent constants.
//
//nolint:paralleltest // forces the process-global SIMD tier, which no two tests may do at once
func TestRendererPrecisionRandomizedCircles(t *testing.T) {
	const (
		shortDraws = 64
		fullDraws  = 512
		// Both digests were measured on amd64 and hold on arm64; see
		// docs/renderer-precision-measurements.md.
		shortHash = "8445513133bf7bd02706dad943f05776e5b1dfe7afdcfe68cb8d46bdfc4682a1"
		fullHash  = "c9220e3e887056ce5e9bd6a3f23ebf11a0bba03694c49be7dbc49b0b7257382a"
	)

	t.Cleanup(fit.ResetTierDetection)

	draws, want := fullDraws, fullHash
	if testing.Short() {
		draws, want = shortDraws, shortHash
	}

	got := precisionRandomDigest(t, draws, 1)
	if got != want {
		t.Errorf("%d draws: digest = %q, recorded %q", draws, got, want)
	}

	for _, tier := range fit.SupportedTiers() {
		if testing.Short() && tier != fit.Tier() {
			continue
		}

		fit.SetForcedTier(tier)

		for _, threads := range precisionShardCounts(71) {
			if digest := precisionRandomDigest(t, draws, threads); digest != got {
				t.Errorf("tier %s, %d shards: digest = %q, want %q", tier, threads, digest, got)
			}
		}

		fit.ResetTierDetection()
	}
}

// TestRendererPrecisionRowSharding asserts both halves of the contract on one
// twelve-circle scene.
//
// Within the process it pins the property the row walk is built on: workers own
// disjoint bands, so the number of bands cannot change a pixel. Across
// processes, the single-threaded render that serves as this sweep's oracle is
// itself pinned to a recorded digest, exactly as every named scene is. Without
// that anchor the sweep would only prove internal consistency, and a scene that
// rendered differently on ARM64 while staying shard-invariant there would still
// pass on both architectures.
//
// GOMAXPROCS is raised for the duration because SetThreads caps at it, and a
// three-processor runner would otherwise reduce every shard count in the sweep
// to three. Sharding correctness does not depend on the bands actually running
// in parallel, so this measures the same property on any host.
//
//nolint:paralleltest // forces the process-global SIMD tier, which no two tests may do at once
func TestRendererPrecisionRowSharding(t *testing.T) {
	const (
		width  = 71
		height = 53
	)

	previous := runtime.GOMAXPROCS(max(runtime.GOMAXPROCS(0), height))

	t.Cleanup(func() { runtime.GOMAXPROCS(previous) })
	t.Cleanup(fit.ResetTierDetection)

	scene := precisionScene{
		name: "sharding", width: width, height: height, canvas: precisionCanvasOpaque,
		circles: precisionRandomScene(newPrecisionRNG(0x5150_1020_5ABD), width, height, 12),
	}

	want, wantCost := precisionRender(scene, 1)

	// The cross-architecture anchor, asserted before this buffer is used as the
	// oracle below.
	recorded, ok := precisionDigests[scene.name]
	if !ok {
		t.Fatalf("scene has no recorded digest; measured %q", precisionDigest(want, wantCost))
	}

	if got := precisionDigest(want, wantCost); got != recorded {
		t.Errorf("digest = %q, recorded %q (cost %v)", got, recorded, wantCost)
	}

	// Every band count from one to one row per worker, plus the values that
	// exercise a band boundary landing on a circle's extreme row.
	shardCounts := []int{1, 2, 3, 5, 7, 8, 11, 16, 17, 32, height - 1, height, height + 1}

	tiers := fit.SupportedTiers()

	//nolint:paralleltest // each subtest renders under a forced tier the loop owns
	for _, tier := range tiers {
		if testing.Short() && tier != fit.Tier() {
			continue
		}

		fit.SetForcedTier(tier)

		for _, threads := range shardCounts {
			t.Run(fmt.Sprintf("%s/shards_%d", tier, threads), func(t *testing.T) {
				got, cost := precisionRender(scene, threads)
				assertPixelsEqual(t, got, want, width, fmt.Sprintf("tier %s, %d shards", tier, threads))

				if cost != wantCost {
					t.Errorf("tier %s, %d shards: cost = %v, want %v", tier, threads, cost, wantCost)
				}
			})
		}

		fit.ResetTierDetection()
	}
}

// TestRendererPrecisionBatchPipelineBoundaries covers the batch pipeline's own
// boundaries rather than the span search's. Two properties are asserted:
//
//   - The accumulated audit stepper keeps a composited prefix instead of
//     replaying the draw order, and planAudit hands runs of that order to
//     several sessions at once. Neither may move a byte or a cost, so the
//     parallel audit must equal the serial one exactly.
//   - compositeParams draws onto a caller-owned canvas without resetting it,
//     which is what lets a retained prefix be reused. The result must equal a
//     full render of the same vector.
//
// The circle count is chosen to cross minAuditChunkCircles*auditChunksPerWorker,
// below which planAudit deliberately stays serial.
//
//nolint:paralleltest // forces the process-global SIMD tier, which no two tests may do at once
func TestRendererPrecisionBatchPipelineBoundaries(t *testing.T) {
	const (
		width   = 64
		height  = 40
		circles = minAuditChunkCircles * auditChunksPerWorker * 2
	)

	reference := precisionReference(width, height)
	base := precisionImage(width, height, 0x5150_1020_0002, true)
	drawn := precisionRandomScene(newPrecisionRNG(0x5150_1020_BA7C), width, height, circles)
	params := encodeCircles(drawn)

	serial := NewCPURendererWithCanvas(reference, base, circles)
	serial.SetThreads(1)

	serialAudit, err := AuditCircleBatch(serial, params)
	if err != nil {
		t.Fatalf("serial AuditCircleBatch: %v", err)
	}

	parallel := NewCPURendererWithCanvas(reference, base, circles)
	parallel.SetThreads(max(2, runtime.GOMAXPROCS(0)))

	parallelAudit, err := AuditCircleBatch(parallel, params)
	if err != nil {
		t.Fatalf("parallel AuditCircleBatch: %v", err)
	}

	if parallelAudit.MSE != serialAudit.MSE {
		t.Errorf("parallel audit MSE = %v, serial = %v", parallelAudit.MSE, serialAudit.MSE)
	}

	if len(parallelAudit.Circles) != len(serialAudit.Circles) {
		t.Fatalf("parallel audit reported %d circles, serial %d", len(parallelAudit.Circles), len(serialAudit.Circles))
	}

	for i := range serialAudit.Circles {
		if parallelAudit.Circles[i] != serialAudit.Circles[i] {
			t.Errorf("circle %d: parallel audit = %+v, serial = %+v", i+1, parallelAudit.Circles[i], serialAudit.Circles[i])
		}
	}

	// An incrementally composited prefix plus its suffix must equal a full
	// render of the whole vector, at every split point around the chunk size.
	full := append([]byte(nil), serial.Render(params).Pix...)

	//nolint:paralleltest // the subtests share one renderer and its reusable canvas
	for _, prefix := range []int{0, 1, minAuditChunkCircles, minAuditChunkCircles * auditChunksPerWorker, circles} {
		t.Run(fmt.Sprintf("prefix_%d", prefix), func(t *testing.T) {
			canvas := serial.initialCanvas()
			serial.compositeParams(canvas, params, prefix)
			serial.compositeParams(canvas, params[prefix*paramsPerCircle:], circles-prefix)
			assertPixelsEqual(t, canvas.Pix, full, width, fmt.Sprintf("prefix %d", prefix))
		})
	}
}

// TestSpanSearchAlwaysCoversNearestSample records a rasterization rule that the
// correctness matrix did not previously reach, and that
// docs/renderer-precision-measurements.md analyses in full.
//
// circleSpanFloat64 and fixedCircleQ16.span both start at int(centerX+0.5) and
// walk outward, so that pixel is painted on every row the disc touches -- even
// on a tangent row where its distance to the center exceeds the radius. On such
// a row the historical bounding-box rasterizer paints nothing, so the two
// disagree by one pixel. It is a property of the center-out search, not of the
// number format: the float64 and the Q16.16 paths do it identically, and so
// does every architecture and tier.
//
// The rule is pinned rather than changed. Changing it would move rendered
// output, and therefore every recorded cost in docs/, for about one row in
// twelve thousand.
//
//nolint:paralleltest // shares the process-global SIMD tier the tests above force
func TestSpanSearchAlwaysCoversNearestSample(t *testing.T) {
	tests := []struct {
		name      string
		centerX   float64
		remaining float64
		width     int
		want      [2]int
	}{
		{name: "tangent_row_half_pixel_center", centerX: 10.5, remaining: 0, width: 21, want: [2]int{11, 12}},
		{name: "tangent_row_integer_center", centerX: 10, remaining: 0, width: 21, want: [2]int{10, 11}},
		{name: "row_narrower_than_half_pixel", centerX: 10.5, remaining: 0.2, width: 21, want: [2]int{11, 12}},
		{name: "row_reaching_both_samples", centerX: 10.5, remaining: 0.25, width: 21, want: [2]int{10, 12}},
	}

	//nolint:paralleltest // shares the process-global SIMD tier the tests above force
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			start, end := circleSpanFloat64(test.centerX, test.remaining, test.width)
			if [2]int{start, end} != test.want {
				t.Errorf("circleSpanFloat64 = [%d,%d), want [%d,%d)", start, end, test.want[0], test.want[1])
			}

			one, two := circleSpanFloat64OnePixel(test.centerX, test.remaining, test.width)
			if [2]int{one, two} != test.want {
				t.Errorf("circleSpanFloat64OnePixel = [%d,%d), want [%d,%d)", one, two, test.want[0], test.want[1])
			}
		})
	}

	// The same rule holds through the production Q16.16 path: a disc whose
	// extreme row reaches no integer sample still paints one pixel there.
	geometry, ok := newFixedCircleQ16(fit.Circle{X: 10.5, Y: 10, R: 1})
	if !ok {
		t.Fatal("newFixedCircleQ16 refused an ordinary circle")
	}

	start, end, intersects := geometry.span(11, 21)
	if !intersects || start != 11 || end != 12 {
		t.Errorf("fixedCircleQ16.span(11) = [%d,%d) intersects=%v, want [11,12) true", start, end, intersects)
	}
}

// TestSpanSearchOverCoverageRate bounds how often the rule above actually
// fires. It is the quantified half of TestSpanSearchAlwaysCoversNearestSample:
// the deviation is real, so the thing worth guarding is its size.
//
// The comparison is against the exact integer interval, computed with
// math.Sqrt rather than by walking, so the oracle shares no code with the
// search. Under-coverage would be a defect of a different kind -- the search
// missing a pixel that is inside the disc -- and is asserted to be impossible.
//
//nolint:paralleltest // shares the process-global SIMD tier the tests above force
func TestSpanSearchOverCoverageRate(t *testing.T) {
	if testing.Short() {
		t.Skip("sweeps 200,000 circles")
	}

	const (
		width   = 513
		height  = 389
		circles = 200_000
		seed    = 0x5150_1020_C0FE
	)

	rng := newPrecisionRNG(seed)
	rows, overCovered, underCovered := 0, 0, 0

	for range circles {
		centerX := rng.unitFloat() * width
		centerY := rng.unitFloat() * height
		radius := fit.MinCircleRadius + rng.unitFloat()*64
		radiusSquared := radius * radius

		for y := range height {
			dy := float64(y) - centerY

			remaining := radiusSquared - dy*dy
			if remaining < 0 {
				continue
			}

			rows++

			start, end := circleSpanFloat64(centerX, remaining, width)
			start = max(start, 0)
			end = min(end, width)

			root := math.Sqrt(remaining)
			wantStart := max(int(math.Ceil(centerX-root)), 0)
			wantEnd := min(int(math.Floor(centerX+root)), width-1) + 1

			painted := end > start
			covered := wantEnd > wantStart

			switch {
			case !covered:
				// No integer sample on this row lies inside the disc.
				if painted {
					overCovered++
				}
			case !painted:
				underCovered++
			case start == wantStart && end == wantEnd:
			case start <= wantStart && end >= wantEnd:
				overCovered++
			default:
				underCovered++
			}
		}
	}

	if underCovered != 0 {
		t.Errorf("span search under-covered %d of %d intersecting rows; want 0", underCovered, rows)
	}

	// Measured at 1,110 of 12,466,238 rows (0.0089%) on both amd64 and arm64.
	// The bound is an order of magnitude above that, so it catches a change of
	// kind rather than a change of a few rows.
	if overCovered > rows/10_000 {
		t.Errorf("span search over-covered %d of %d intersecting rows; want at most 0.01%%", overCovered, rows)
	}

	t.Logf("span search over-covered %d of %d intersecting rows (%.4f%%), under-covered %d",
		overCovered, rows, 100*float64(overCovered)/float64(rows), underCovered)
}
