package server

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/cwbudde/mayflycirclefit/internal/store"
	"github.com/cwbudde/mayflycirclefit/internal/ui"
)

// TestStaticRouteServesTheIslandBundle pins the route wiring rather than the
// handler behavior, which internal/ui already covers. /static/ is a new
// surface on the trusted-local boundary, so the mux must reach it and the mux
// must not have swallowed it into the catch-all "/" handler.
func TestStaticRouteServesTheIslandBundle(t *testing.T) {
	root := t.TempDir()
	persistence, err := store.NewFSStore(root)
	if err != nil {
		t.Fatal(err)
	}
	server := NewServerWithOptions("localhost:0", persistence, ServerOptions{DataRoot: root})

	recorder := httptest.NewRecorder()
	server.Handler().ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, ui.BundleURL(), nil))

	if recorder.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d", recorder.Code, http.StatusOK)
	}
	if got, want := recorder.Header().Get("Content-Type"), "text/javascript; charset=utf-8"; got != want {
		t.Fatalf("Content-Type = %q, want %q", got, want)
	}
	if !strings.HasPrefix(recorder.Body.String(), "// Code generated by scripts/bundle-web.sh") {
		t.Error("the /static/ route did not serve the embedded bundle")
	}
}

// TestUnknownStaticAssetIsNotFound guards against the mux falling back to the
// "/" handler, which would answer a missing asset with a 200 and an HTML page.
func TestUnknownStaticAssetIsNotFound(t *testing.T) {
	root := t.TempDir()
	persistence, err := store.NewFSStore(root)
	if err != nil {
		t.Fatal(err)
	}
	server := NewServerWithOptions("localhost:0", persistence, ServerOptions{DataRoot: root})

	recorder := httptest.NewRecorder()
	server.Handler().ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, "/static/missing.js", nil))

	if recorder.Code != http.StatusNotFound {
		t.Fatalf("status = %d, want %d", recorder.Code, http.StatusNotFound)
	}
}
