#!/usr/bin/env bash
# Bundle the React islands in web/src into the committed asset that
# internal/ui embeds. esbuild runs as a Go tool (see the tool block in
# go.mod), so the only thing npm supplies is web/node_modules; the pinned
# esbuild version plus web/package-lock.json are what make the output
# reproducible enough for the drift gate to be meaningful.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"
cd "$repo_root"

if [[ ! -d web/node_modules ]]; then
	printf 'web/node_modules is missing; run `npm ci` in web/ first.\n' >&2
	exit 1
fi

mkdir -p internal/ui/static

go tool esbuild web/src/dashboard.tsx \
	--bundle \
	--minify \
	--format=esm \
	--target=es2020 \
	--jsx=automatic \
	--define:process.env.NODE_ENV='"production"' \
	--legal-comments=none \
	--banner:js='// Code generated by scripts/bundle-web.sh from web/src. DO NOT EDIT.' \
	--log-level=warning \
	--outfile=internal/ui/static/dashboard.js
