package ui

import (
	"bytes"
	"context"
	"strings"
	"testing"
	"time"
)

func TestJobReportPageRendersSelfContainedContent(t *testing.T) {
	ended := time.Date(2026, time.August, 14, 1, 2, 3, 0, time.UTC)
	report := JobReport{
		ID: "12345678-1234-1234-1234-123456789abc", State: "completed", Mode: "joint",
		Colormap: "magma", RefPath: "assets/reference.png", Circles: 1, Iterations: 42,
		Evaluations: 420, Cost: 12.345678, PSNR: "37.22 dB", SSIM: "0.9876",
		StartTime: ended.Add(-time.Minute), EndTime: &ended, ElapsedSec: 60, GeneratedAt: ended.Add(time.Second),
		ReferenceDataURI: "data:image/png;base64,cmVm", BestDataURI: "data:image/png;base64,YmVzdA==",
		DifferenceDataURI: "data:image/png;base64,ZGlmZg==",
		Parameters: []CircleParameter{{
			Number: 1, X: 12.25, Y: 24.5, Radius: 3.75,
			Red: 1, Green: 0.5, Blue: 0, Opacity: 0.75,
		}},
	}

	var output bytes.Buffer
	if err := JobReportPage(report).Render(context.Background(), &output); err != nil {
		t.Fatalf("render report: %v", err)
	}
	body := output.String()
	for _, marker := range []string{
		"<!doctype html>", "MayFlyCircleFit Report", report.ID, "assets/reference.png",
		"37.22 dB", "0.9876", "magma", "12.345678", "1m 0s", "2026-08-14T01:02:03Z",
		"data:image/png;base64,cmVm", "data:image/png;base64,YmVzdA==", "data:image/png;base64,ZGlmZg==",
		">12.2500<", ">24.5000<", ">3.7500<", "255, 128, 0", ">0.7500<",
		"@media print", "Self-contained report generated by MayFlyCircleFit",
	} {
		if !strings.Contains(body, marker) {
			t.Errorf("rendered report missing %q", marker)
		}
	}
	if strings.Contains(body, `<script`) || strings.Contains(body, `<link`) {
		t.Error("rendered report contains a script or external stylesheet")
	}
}

func TestJobReportPageOmitsMissingEndTime(t *testing.T) {
	report := JobReport{
		ID: "12345678-1234-1234-1234-123456789abc", StartTime: time.Now(), GeneratedAt: time.Now(),
		ReferenceDataURI: "data:image/png;base64,AA==", BestDataURI: "data:image/png;base64,AA==",
		DifferenceDataURI: "data:image/png;base64,AA==",
	}
	var output bytes.Buffer
	if err := JobReportPage(report).Render(context.Background(), &output); err != nil {
		t.Fatal(err)
	}
	if strings.Contains(output.String(), `<div class="label">Ended</div>`) {
		t.Error("report rendered an end time for an active job")
	}
}
