name: ci-build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Ordinary build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
      - run: go build ./...
